### ISSUE TITLE
Could not save settings Error: Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: settings.key: INSERT INTO `settings` (`key`, `value`) VALUES (?, ?): plugin-com.andrejilderda.macOSTheme.appearance,light-with-dark-sidebar

### ISSUE THREAD

**Issue by linton1024** [andrejilderda/joplin-macos-native-theme#147]
2024-09-12 16:20:46: ResourceService::indexNoteResources: Start
2024-09-12 16:20:46: joplin.plugins: Starting plugin: com.andrejilderda.macOSTheme
2024-09-12 16:20:47: joplin.plugins: Starting plugin: com.whatever.quick-links
2024-09-12 16:20:47: joplin.plugins: Starting plugin: io.github.jackgruber.backup
2024-09-12 16:20:47: joplin.plugins: Starting plugin: joplin.plugin.app.locker
2024-09-12 16:20:47: joplin.plugins: Starting plugin: joplin.plugin.lannerkr.EncDecV3
2024-09-12 16:20:47: joplin.plugins: Starting plugin: org.joplinapp.plugins.joplin-calendar
2024-09-12 16:20:47: joplin.plugins: Starting plugin: plugin.calebjohn.rich-markdown
2024-09-12 16:20:47: PostMessageService: [warn] Cannot receive message because no viewMessageHandler was found {"pluginId":"org.joplinapp.plugins.joplin-calendar","viewId":"plugin-view-org.joplinapp.plugins.joplin-calendar-calendar_panel","contentScriptId":null,"from":"plugin","to":"userWebview","id":"plugin_17261292475920.9120032653464829","content":{"type":5}}
2024-09-12 16:20:47: joplin.plugins: Finished running onStart handler: joplin.plugin.lannerkr.EncDecV3 (Took 352ms)
2024-09-12 16:20:47: DecryptionWorker: completed decryption.
2024-09-12 16:20:47: joplin.plugins: Finished running onStart handler: joplin.plugin.app.locker (Took 361ms)
2024-09-12 16:20:47: useFormNote: Sync has finished and note has never been changed - reloading it
2024-09-12 16:20:47: joplin.plugins: Finished running onStart handler: com.whatever.quick-links (Took 873ms)
2024-09-12 16:20:48: joplin.plugins: Finished running onStart handler: org.joplinapp.plugins.joplin-calendar (Took 1040ms)
2024-09-12 16:20:48: joplin.plugins: Finished running onStart handler: plugin.calebjohn.rich-markdown (Took 1447ms)
2024-09-12 16:20:49: joplin.plugins: Finished running onStart handler: com.andrejilderda.macOSTheme (Took 2128ms)
2024-09-12 16:20:49: RevisionService: maintenance: Starting...
2024-09-12 16:20:49: RevisionService: maintenance: Service is enabled
2024-09-12 16:20:49: RevisionService: collectRevisions: Created revisions for 0 notes
2024-09-12 16:20:49: RevisionService: maintenance: Done in 140ms
2024-09-12 16:20:49: joplin.plugins: Finished running onStart handler: io.github.jackgruber.backup (Took 2309ms)
2024-09-12 16:20:49: ResourceService::indexNoteResources: Completed
2024-09-12 16:20:49: models/Setting: [error] Could not save settings Error: Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: settings.key: INSERT INTO `settings` (`key`, `value`) VALUES (?, ?): plugin-com.andrejilderda.macOSTheme.appearance,light-with-dark-sidebar
Code: SQLITE_CONSTRAINT
Error: Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: settings.key: INSERT INTO `settings` (`key`, `value`) VALUES (?, ?): plugin-com.andrejilderda.macOSTheme.appearance,light-with-dark-sidebar
    at DatabaseDriverNode.sqliteErrorToJsError (C:\Users\Admin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\database-driver-node.js:23:18)
    at JoplinDatabase.sqliteErrorToJsError (C:\Users\Admin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\database.js:36:30)
    at JoplinDatabase.<anonymous> (C:\Users\Admin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\database.js:141:36)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\Admin\AppData\Local\Programs\Joplin\resources\app.asar\node_modules\@joplin\lib\database.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Joplin 3.0.15 (prod, win32)

客户端 ID: 1abebd77ed9f462d93a6704e2b204b82
同步版本：3
配置文件版本：47
支持的密钥链：是

修订：598677b

Backup: 1.4.2
EncDecModeV3: 3.0.1
Joplin Calendar: 1.2.0
joplin plugin app screen locker: 1.0.9
macOS theme: 1.5.8
Note Tabs: 1.4.0
Quick Links: 1.3.2
Rich Markdown: 0.15.0

**Comment by andrejilderda** [comment]
I guess this was fixed as I'm unable to reproduce your issue with the latest version of Joplin (3.3.12) and the theme (v1.5.16).
